### ISSUE TITLE
неудобный API

### ISSUE THREAD

**Issue by TheAirBlow** [VoxelHax/software-archive#1]
Все в репо должен быть только один JSON файл, а все бинарники в Releases.
В руте репо `info.json`:
```json5
{
  "bungeekit": {
    "title": "BungeeKit",
    "short_description": "BungeeCord IP-forwarding login spoofer",
    "full_description": "BungeeKit is an util, that allows you to connect servers with BungeeCord mode enabled. It also allows to spoof connection host and player IP.",
    "versions": {
      // Этого нету в оригинальном JSON,
      // что делать "API" неюзабельным
      "all": [ "3.2", "т.д." ] // все версии
      "latest": "3.2" // последняя версия
    }
  },
  "т.д.": {
    // все остальное
  }
}
```

В Releases бинарники идут таким образом:
1) Название тэга - "ключ" JSON (`"это ключ": { /* это значение */ }`), тире и версия: `bungeekit-3.2`
2) Бинарник - чисто ID и .exe: `bungeekit.exe`

Таким образом намного проще делать список изменений, и в целом юзать репо.

~~мне просто было скучно и решил зайти на твой гх~~

**Comment by Rikonardo** [comment]
https://github.com/VoxelHax/software-archive/commit/42bb1ad8cdd26f4afcc2b253034cb3297c649ca6 Сделал гх экшн, который генерит такой JSON и сейвит в отдельную репу (https://github.com/VoxelHax/software-archive-api)

Можно получить JSON запросом на URL:
```
https://raw.githubusercontent.com/VoxelHax/software-archive-api/main/api.json
```
